In [ ]:
#Go Emotions: Google Emotions Dataset 
import kagglehub

path = kagglehub.dataset_download("shivamb/go-emotions-google-emotions-dataset")
print("Path to dataset files:", path)

In [ ]:
#Reddit dataset: r/depression and r/SuicideWatch - 

import kagglehub
path = kagglehub.dataset_download("xavrig/reddit-dataset-rdepression-and-rsuicidewatch")

print("Path to dataset files:", path)

In [ ]:
#Empathetic Dialogues (Facebook AI) 25k 
import kagglehub

# Download latest version
path = kagglehub.dataset_download("atharvjairath/empathetic-dialogues-facebook-ai")

print("Path to dataset files:", path)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

print("VS Code Jupyter is using the venv correctly!")
print(pd.__version__)

VS Code Jupyter is using the venv correctly!
2.1.1

In [11]:
dataset_path = "/Users/amanthakur/Documents/WORK/Major_Project/Dataset/Final/"

# Pick a CSV file from the folder
google_csv = os.path.join(dataset_path,"cleaned_go_emotions_dataset_clean.csv")  
facebook_csv = os.path.join(dataset_path,"emotion-emotion_69_clean.csv")
reddit_csv =  os.path.join(dataset_path,"reddit_depression_suicidewatch_new_final.csv")  

# Load into pandas DataFrame
df_google_csv = pd.read_csv(google_csv)
df_facebook_csv = pd.read_csv(facebook_csv)
df_reddit_csv = pd.read_csv(reddit_csv)

# Show first 5 rows
df_google_csv.head()

,text,example_very_unclear,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,...,nervousness,optimism,pride,realization,relief,remorse,sadness,surprise,neutral,labels
0,That game hurt.,False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,['sadness']
1,"You do right, if you don't care then fuck 'em!",False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,['neutral']
2,Man I love reddit.,False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,['love']
3,"[NAME] was nowhere near them, he was by the Fa...",False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,['neutral']
4,Right? Considering it’s such an important docu...,False,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,['gratitude']

In [ ]:
# GOOGLE CSV
# Number of rows and columns
print("Shape of dataset:", df_google_csv.shape)

# Column names
print("Columns:", df_google_csv.columns.tolist())

# Data types of each column
print(df_google_csv.dtypes)

Shape of dataset: (151755, 31)
Columns: ['text', 'example_very_unclear', 'admiration', 'amusement', 'anger', 'annoyance', 'approval', 'caring', 'confusion', 'curiosity', 'desire', 'disappointment', 'disapproval', 'disgust', 'embarrassment', 'excitement', 'fear', 'gratitude', 'grief', 'joy', 'love', 'nervousness', 'optimism', 'pride', 'realization', 'relief', 'remorse', 'sadness', 'surprise', 'neutral', 'labels']
text                    object
example_very_unclear      bool
admiration               int64
amusement                int64
anger                    int64
annoyance                int64
approval                 int64
caring                   int64
confusion                int64
curiosity                int64
desire                   int64
disappointment           int64
disapproval              int64
disgust                  int64
embarrassment            int64
excitement               int64
fear                     int64
gratitude                int64
grief                    int64
joy                      int64
love                     int64
nervousness              int64
optimism                 int64
pride                    int64
realization              int64
relief                   int64
remorse                  int64
sadness                  int64
surprise                 int64
neutral                  int64
labels                  object
dtype: object

In [10]:
df_facebook_csv.head()

,Situation,emotion,empathetic_dialogues,labels
0,i remember going to the fireworks with my best...,sentimental,customer :i remember going to see the firework...,"was this a friend you were in love with, or ju..."
1,i used to scare for darkness,afraid,customer : it feels like hitting to blank wall...,oh ya? i don't really see how
2,i showed a guy how to run a good bead in weldi...,proud,customer :hi how are you doing today\nagent :,doing good.. how about you
3,i have always been loyal to my wife.,faithful,customer :i have never cheated on my wife.\nag...,"and thats something you should never do, good ..."
4,a recent job interview that i had made me feel...,terrified,customer :job interviews always make me sweat ...,don't be nervous. just be prepared.

In [ ]:
# FACEBOOK CSV
# Number of rows and columns
print("Shape of dataset:", df_facebook_csv.shape)

# Column names
print("Columns:", df_facebook_csv.columns.tolist())

# Data types of each column
print(df_facebook_csv.dtypes)

Shape of dataset: (19304, 4)
Columns: ['Situation', 'emotion', 'empathetic_dialogues', 'labels']
Situation               object
emotion                 object
empathetic_dialogues    object
labels                  object
dtype: object

In [20]:
df_reddit_csv.head()

   Unnamed: 0                                               text         label
0           0  i recently went through a breakup and she said...    depression
1           1  i do not know how to navigate these feelings n...    depression
2           2  so i have been with my bf for 5 months  and he...    depression
3           3  i am so exhausted of this. just when i think i...  suicidewatch
4           4  i have been severly bullied since i was 5 till...    depression

In [ ]:
# REDDIT CSV
# Number of rows and columns
print("Shape of dataset:", df_reddit_csv.shape)

# Column names
print("Columns:", df_reddit_csv.columns.tolist())

# Data types of each column
print(df_reddit_csv.dtypes)

Shape of dataset: (20364, 3)
Columns: ['Unnamed: 0', 'text', 'label']
Unnamed: 0     int64
text          object
label         object
dtype: object

In [ ]:
# Count missing values per column
# REDDIT CSV
'''missing_values = df_reddit_csv.isnull().sum()
print("Missing values per column:\n", missing_values)
'''
# FACEBOOK CSV
'''missing_values = df_facebook_csv.isnull().sum()
print("Missing values per column:\n", missing_values)
'''
# GOOGLE CSV
'''missing_values = df_google_csv.isnull().sum()
print("Missing values per column:\n", missing_values)
'''

Missing values per column:
 text                    0
example_very_unclear    0
admiration              0
amusement               0
anger                   0
annoyance               0
approval                0
caring                  0
confusion               0
curiosity               0
desire                  0
disappointment          0
disapproval             0
disgust                 0
embarrassment           0
excitement              0
fear                    0
gratitude               0
grief                   0
joy                     0
love                    0
nervousness             0
optimism                0
pride                   0
realization             0
relief                  0
remorse                 0
sadness                 0
surprise                0
neutral                 0
labels                  0
dtype: int64

In [19]:
# Replace 'column_name' with your actual column
null_rows = df_reddit_csv[df_reddit_csv['label'].isnull()]

# Show all rows with nulls in that column
print(null_rows)

Empty DataFrame
Columns: [Unnamed: 0, text, label]
Index: []

In [ ]:
#deleting null rows 

#df_reddit_csv = df_reddit_csv.dropna()